---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/venki231blr/kind-argocd-example.git
    targetRevision: HEAD
    path: demo-100/my-app
  destination:
    server: https://kubernetes.default.svc